# Generated by Django 5.0.1 on 2024-01-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgs',
            old_name='user',
            new_name='username',
        ),
    ]
