# Generated by Django 5.0.1 on 2024-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_imgs_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='binary',
            field=models.TextField(),
        ),
    ]
