# Generated by Django 5.0.1 on 2024-01-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_imgs_binary'),
    ]

    operations = [
        migrations.CreateModel(
            name='imgs_feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.TextField()),
                ('binary', models.TextField()),
                ('date', models.DateField()),
                ('comments', models.TextField()),
            ],
        ),
    ]
