# Generated by Django 5.0.1 on 2024-02-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_imgs_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs_feed',
            name='date',
            field=models.TextField(),
        ),
    ]
