# Generated by Django 5.0.1 on 2024-02-05 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_imgs_feed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgs',
            name='binary',
        ),
        migrations.AddField(
            model_name='imgs',
            name='binary_bg',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='imgs',
            name='binary_photo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='username',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgs_feed',
            name='auth',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgs_feed',
            name='binary',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgs_feed',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='imgs_feed',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
