# Generated by Django 5.0.1 on 2024-02-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_imgs_binary_imgs_binary_bg_imgs_binary_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
